[workspace]
members = [
    'node',
    'pallets/threshold-signature',
    'pallets/threshold-signature/rpc',
    'pallets/threshold-signature/rpc/runtime-api',
    'runtime',
]
[profile.release]
panic = 'unwind'
